# Generated by Django 3.2.5 on 2024-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_auto_20240108_0611"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30, verbose_name="user name"),
        ),
    ]
