# Generated by Django 3.2.5 on 2024-01-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_auto_20240108_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="slug",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
